### PR TITLE
Fix jmpFwd in neighborhoods

### PR DESCRIPTION
**Pull request by dietzc**
They were all a bit buggy. Test added and made test pass.

### CODE REVIEW

**Comment by Squareys** [comment]
@dietzc http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html ;)

**Comment by dietzc** [comment]
hehe. no.

**Comment by ctrueden** [comment]
I agree with @Squareys ;-)

**Comment by dietzc** [comment]
pff

**Pull request merged**
