### PR TITLE
Add HessianMatrix and TensorEigenValues

### PR DESCRIPTION
**Pull request by hanslovsky**
- Use PartialDerivative to generate linear representation of upper
   triangular Hessian matrix
 - Add TensorEigenValues class to compute eigenvalues on tensors such as
   the Hessian matrix included in this commit.hessian eigenvalues

This pull request rebases all commits in and closes #29.

### CODE REVIEW

**Comment by tpietzsch** [comment]
thanks @hanslovsky, great work!

**Comment by tpietzsch** [comment]
@hanslovsky Can you please fix the javadoc
```
[ERROR] /home/travis/build/imglib/imglib2-algorithm/src/main/java/net/imglib2/algorithm/linalg/matrix/RealCompositeMatrix.java:47: error: reference not found
[ERROR] *         {@link RealMatrix} that reads data from {@link Composite} (non-copy).
[ERROR] ^
[ERROR] /home/travis/build/imglib/imglib2-algorithm/src/main/java/net/imglib2/algorithm/linalg/matrix/RealCompositeSquareMatrix.java:44: error: reference not found
[ERROR] *         Square {@link RealMatrix} that reads data from {@link Composite}
[ERROR] ^
[ERROR] /home/travis/build/imglib/imglib2-algorithm/src/main/java/net/imglib2/algorithm/linalg/matrix/RealCompositeSymmetricMatrix.java:44: error: reference not found
[ERROR] *         Symmetric {@link RealMatrix} that reads data from {@link Composite}
```

I guess, RealMatrix is left over from before ojAlgo?

**Comment by hanslovsky** [comment]
Yes, that was from before ojAlgo, I will fix it.
I tried to ensure that it builds running `mvn clean build` before creating the final PR but that was not enough, apparently. What maven command would I need to run to replicate the behavior on travis? Probably a question for @ctrueden

**Comment by tpietzsch** [comment]
`mvn javadoc:javadoc`

**Pull request merged**
