### PR TITLE
Implement getters for construction parameters in all Shapes

### PR DESCRIPTION
**Pull request by Squareys**
Hello everybody, Hello @tpietzsch !

I implemented the changes suggested in #5.

Greetings, Squareys

### CODE REVIEW

**Comment by dietzc** [comment]
I'm wondering if there could be a `public Interval getBoundingBox()` method for each `Shape`, instead of providing `getSpan` or `getRadius`. It just feels a bit more consistent?

**Comment by Squareys** [comment]
@dietzc See #5 for previous discussion. Both could be provided. I only implemented the one, since it is directly relevant for what I'm working on in imagej-ops.

**Comment by dietzc** [comment]
thanks @Squareys

**Comment by tpietzsch** [comment]
thanks @Squareys

**Pull request merged**
