### PR TITLE
Bump imglib2 dependency to 5.0.0

### PR DESCRIPTION
**Pull request by hanslovsky**
This bumps the imglib2 dependency to new major version 5. Only one test case needed adaption and all the tests succeed.

### CODE REVIEW

**Comment by ctrueden** [comment]
@hanslovsky @tpietzsch What are the backwards incompatible changes in imglib2 5.0.0? Has anyone run the melting pot on Fiji with imglib2 5.0.0 yet? Does anything break? (If not, I will do it during the SciView hackathon, since I will be improving the melting pot script and melting down Fiji repeatedly anyway to address other incompatibilities.)

**Comment by hanslovsky** [comment]
@ctrueden As far as I can tell, everything should be pretty smooth as long as you use imglib2 primitive type equivalents (`ByteType` etc). I am updating all projects that I depend on to figure out what kind of problems we may run into. So far I have done the update for
 - [n5-label-multisets](https://github.com/saalfeldlab/n5-label-multisets/tree/imglib2-5)
 - [n5-label-multisets-spark](https://github.com/saalfeldlab/n5-label-multisets-spark/tree/imglib2-v5)
 - [n5-imglib2](https://github.com/saalfeldlab/n5-imglib2/pull/4)
 - working on bdv-core

It is probably good advise to keep all these PRs/branches open for a while before merging into the respective master branches.

**Comment by hanslovsky** [comment]
See also imglib/imglib2#204

**Comment by hanslovsky** [comment]
Fixed in 97360f3653d4eb661dae2e84924ddcdb291f3200

**Pull request closed without merging**
