### PR TITLE
Change visibility of MorphologyUtils methods

### PR DESCRIPTION
**Pull request by LeonYang5114**
Methods with package visibility are changed to be public, so that other packages/projects could use.

### CODE REVIEW

**Comment by ctrueden** [comment]
This helps the Ops project in particular, which otherwise has to recapitulate this code in its own utility class.

**Comment by tpietzsch** [comment]
@tinevez are you ok with this?

**Comment by tinevez** [comment]
The methods you make visible are particularly ugly, notably the subAA and so on. Are YOU ok with this?

**Comment by tpietzsch** [comment]
I have no opinion, I'm not familiar with the code. imglib2-algorithms is not out of beta, so I have no big reservations about adding public API that may be removed later. @ctrueden @LeonYang5114 maybe you could elaborate on why this is required exactly?

**Comment by LeonYang5114** [comment]
I am migrating the morphology code from imglib2-algorithm to imagej-ops, and actually `computeTargetImageDimensionsAndOffset` is needed in handling the padding and alignment. The method is not complicated, but it would be nice to reuse code.

I make others methods also public just because I thought that it might make things consistent. I will modify the PR so that only the method I need is public, if you want.

I recognize that some methods in that utility class is not specific to morphology e.g. `copyCropped`, `subXXX`, and some are almost duplicate, e.g. `getSuitableFactory` vs `net.imglib2.util.Util#getArrayOrCellImgFactory`, `getTypeFromInterval` vs `net.imglib2.util.Util#getTypeFromInterval`. This utility class might need some rework.

**Comment by tpietzsch** [comment]
> I make others methods also public just because I thought that it might make things consistent. I will modify the PR so that only the method I need is public, if you want.

Yes, I would prefer that.

**Comment by LeonYang5114** [comment]
Please check if this works.

**Pull request merged**
