### PR TITLE
Fix rectangle neighborhood jumpFwd

### LINKED ISSUE #6: RectangleNeighborhoodCursor.jumpFwd(1) results in incorrect position.
Hi @tpietzsch !

I believe I found a bug in RectangleNeighborhoodCursor:

On a fresh `shape.neighborhoodsSafe(img).localizingCursor()` `fwd()` results in position `[0, 0, 0]`, but
`jumpFwd(1)` results in position `[2, 0, 0]`.

I wrote a simple test for this: [here](https://github.com/Squareys/imglib2-algorithm/blob/test-rectangle-shape/src/test/java/net/imglib2/algorithm/neighborhood/RectangleShapeTest.java)

When letting the cursor run through the entire img with `.jumpFwd(1)`, an `ArrayIndexOutOfBoundsException` is thrown.

Greetings, Squareys

### PR DESCRIPTION
**Pull request by Squareys**
Hello everybody!

@dietzc and I made an effort to fix #6 . This PR adds a test for `RectangleShape` and includes a fix for `jumpFwd()` of `RectangleNighborhoodCursor`.

@axtimwalde Would you please review? I heard @tpietzsch is currently not available.

Greetings, 
Squareys (Jonathan)

### CODE REVIEW

**Comment by dietzc** [comment]
or maybe @tinevez, could you also quickly check if our changes make sense? you know the code of  `Neighborhood`s as well!

**Comment by tinevez** [comment]
CAn you give me an extra day for review? I just came back from the Country.

**Comment by dietzc** [comment]
of course!

**Comment by tinevez** [comment]
Looks good to me. 
I am really sorry for the mess I have made.

**Comment by dietzc** [comment]
which mess? :-) thanks for taking a look at it. you think we could merge? @axtimwalde any comments?

**Comment by dietzc** [comment]
@tpietzsch allowed it. merged. :+1:

**Pull request merged**
