### PR TITLE
Specialized cursor for RectangleNeighborhoods

### PR DESCRIPTION
**Pull request by stelfrich**
The `IntegralCursor` returns specific corner values of `RectangleNeighborhood`s that can be used for computations on integral images. 

In the 2D example the values at the following positions are returned by `IntegralCursor`:
* (neighMin, neighMin)
* (neighMax-1, neighMin)
* (neighMin, neighMax-1)
* (neighMax-1, neighMax-1)

I would rather have it return the values at the corner positions (and call it CornerCursor) but that renders it effectively useless for use with local operations on integral images. The problem is that for computing the mean in a `RectangleNeighborhood` of an image, values from a `RectangleNeighborhood` with `span+1` at the positions returned by the `IntegralCursor` are required.

### CODE REVIEW

**Comment by dietzc** [comment]
I didn't have time do to a close review (I think @tpietzsch is the best person to do the review here), but can you apply the imglib2 style for all your classes? it can be found in https://github.com/imglib/imglib2/tree/master/doc. This would be great!

**Comment by stelfrich** [comment]
> but can you apply the imglib2 style for all your classes?

@dietzc I have applied a _Source > Format_ and _Source > Clean up_ in the latest commit with the settings applied in Eclipse Mars. Is that the desired outcome? I am asking because there were some discrepancies with my configuration (project specific settings don't necessarily seem to overwrite global settings..).

**Comment by dietzc** [comment]
did you first set the checkstyle of imglib2-core?

**Comment by stelfrich** [comment]
> did you first set the checkstyle of imglib2-core?

Here is what I did:

1. Right click imglib2-algorithm > Properties > Java Code Style > Clean Up > Import imglib2-eclipse-clean-up-style.xml
2. Right click imglib2-algorithm > Properties > Java Code Style > Formatter > Import imglib2-eclipse-mars-clean-up-formatter-style.xml
3. Source > Format
4. Source > Clean up

I have repeated the procedure just now and there's no changes (neglecting the whitespaces in the header).

**Comment by dietzc** [comment]
It seems I took a look at the wrong commit. thanks.

**Comment by stelfrich** [comment]
Short recap of a discussion with @dietzc and @axtimwalde in Gitter:

- [ ] Pass `Neighborhood` to `IntegralCursor`
- [ ] Move `IntegralCursor` to https://github.com/imglib/imglib2-algorithm/tree/integralCursor/src/main/java/net/imglib2/algorithm/integral

Was there a decision to rename `IntegralCursor` to `CornerCursor` or is that obsolete with the move to _src/main/java/net/imglib2/algorithm/integral_?

**Comment by dietzc** [comment]
> Was there a decision to rename IntegralCursor to CornerCursor or is that obsolete with the move to src/main/java/net/imglib2/algorithm/integral?

I suggest to keep the name `IntegralCursor`, as it now lives in the very same package.

**Comment by stelfrich** [comment]
I have implemented the changes minus the optional rename. I had to extend the interface of `RectangleNeighborhood` to get the `sourceRandomAccess` because `IntegralCursor` is no longer an inner class.

**Comment by tpietzsch** [comment]
@stelfrich @dietzc Hi, I just had a look at it for the first time, sorry for long delay... To be honest, I don't know what the point of this is. Why piggyback on `RectangleNeighborhood`, not just make a new neighborhood (respectively shape) whose cursors iterate the rectangle corners (similar JY's `DiamondTipsNeighborhood`; could possibly extend `RectangleNeighborhood`)? I need more context. How do you want it to be used?

**Comment by stelfrich** [comment]
> To be honest, I don't know what the point of this is

The `IntegralCursor` will most be used in conjunction with integral images for computations of mean, standard deviation, variance (hence the move to `net.imglib2.algorithm.integral` in the latest commit). For those computations, only 2^dim values from an integral image are required, which are exactly the values returned by the `IntegralCursor`.

Having a new neighborhood with this implementation as `LocalCursor` is possible but seems like a lot of code duplication to me (see `DiamondNeighborhood*` and `DiamondTipNeighborhood*` classes). With the proposed implementation, we are adding one class and a getter in `RectangleNeighborhood` instead.

Does this make sense?

**Comment by tpietzsch** [comment]
> @tpietzsch The IntegralCursor will most likely only be used in conjunction with integral images for computations of mean, standard deviation, variance (hence the move to net.imglib2.algorithm.integral in the latest commit). For those computations, only 2^dim values from an integral image are required, which are exactly the values returned by the IntegralCursor.

Hmm, that much I guessed...  My question is more along the lines: where would it be used in code? Is this user facing or just used internally, e.g., by some (yet to be written) accessor that provides the mean, standard deviation, variance, for a specific window size?

> Having a new neighborhood with this implementation as LocalCursor is possible but seems like a lot of code duplication to me (see DiamondNeighborhood* and DiamondTipNeighborhood* classes). With the proposed implementation, we are adding one class and a getter in RectangleNeighborhood instead.

That depends on the answer to the above question. If it is intended to be exposed to users, I would go the extra-mile and create a proper accessors, accessible, etc. It could extend the RectangleShape stuff without all that much code duplication, although it would be certainly more that the single "IntegralCursor".

Independent of all this, regarding the actual code of `IntegralCursor`:

- Returning `Vector< Integer >` is bad. `ArrayList<Integer>` is better, and probably best is simply `int[]`.
- Because you increment `index` at the end of `fwd()`, `getCornerInteger` and `getCornerVector` will return wrong results.
- `fwd()` can most likely made much more efficient if you do not do a full `source.setPosition(long[])` every time but instead setPositions for the dimensions that change.
- Currently, everything that you do in `reset()` except `index = 0;` is pointless because of the full `setPosition` in `fwd()`. If `fwd()` is changed to be more efficient, this too has to be revised. Otherwise should be removed.

**Comment by stelfrich** [comment]
> Is this user facing or just used internally

It is used internally in some ops. The user just decides that he wants, for example, to apply a local threshold to an image providing the name of the method, a `Shape`, and an `OutOfBoundsFactory`. In the end, there will be two implementations: a "default" one and one based on integral images when the `shape instanceof RectangleShape`. All in all, the computation of the integral image and the application of `Integral*` ops is hidden from the user.

> Independent of all this, regarding the actual code of IntegralCursor

Thanks for the comments, @tpietzsch.

**Comment by tpietzsch** [comment]
> It is used internally in some ops. The user just decides that he wants, for example, to apply a local threshold to an image providing the name of the method, a Shape, and an OutOfBoundsFactory. In the end, there will be two implementations: a "default" one and one based on integral images when the shape instanceof RectangleShape. All in all, the computation of the integral image and the application of Integral* ops is hidden from the user.

Ok, that makes sense.

Regarding my comment
> fwd() can most likely made much more efficient if you do not do a full source.setPosition(long[]) every time but instead setPositions for the dimensions that change.

If you want to dig into this, have a look at `net.imglib2.interpolation.randomaccess.NLinearInterpolator`. Using gray code patterns you can make it work with only changing one dimension per `fwd()`. This will alter the order in which corners are visited, but algos should be able to deal with that

**Comment by stelfrich** [comment]
> Independent of all this, regarding the actual code of `IntegralCursor`

I have addressed your comments in the latest commit @tpietzsch.

> Ok, that makes sense.

You can take a look at the [`IntegralMean`](https://github.com/stelfrich/imagej-ops/blob/dbd4c5f058201c117f2eacc7496d88c037b8fc3a/src/main/java/net/imagej/ops/stats/IntegralMean.java#L77-L88) implementation if you like. The computation is independent of the iteration order of the cursor and the dimension.

**Comment by stelfrich** [comment]
Any news on this @tpietzsch? We could move the `IntegralCursor` to Ops if you feel that imglib is not the right place for it. If there are any concerns regarding the implementation - I'd be happy to address them.

I have implemented integral versions of local thresholding ops that benefit from (and rely on) this PR.

**Comment by tpietzsch** [comment]
@stelfrich Did you test this and could you please also commit the tests?
Here are some comments:
- javadoc on iteration order https://github.com/imglib/imglib2-algorithm/pull/17/files#diff-03b370b9393245a7920a44a5739022a1R49 is not correct anymore.
- https://github.com/imglib/imglib2-algorithm/pull/17/files#diff-03b370b9393245a7920a44a5739022a1R103 ff are more verbose than necessary. `source` is `Positionable`, so `neighborhood.min( source );` will do the job.
- You do not reset `code` in `reset()` or copy it in the copy constructor.

These final ones are clearly bugs, which makes me wonder how thoroughly you tested this.

As a general remark (which probably no one will read buried in here, but anyway):
Please, do not mis-use pull-requests as a means of getting cheap code reviews and debugging. PRs should be for stuff that is about ready to get merged, not for trying ideas and evolving code that is still under heavy development. This would be better discussed and developed in an issue first.

**Comment by tpietzsch** [comment]
@stelfrich Recently, @axtimwalde started to look into integral images, I wonder how far along that is and how it would influence this PR. Can you comment on progress @axtimwalde?

**Comment by axtimwalde** [comment]
@tpietzsch @stelfrich During my attempt to implement an image integrator I found a conceptual issue in the Ops framework that @ctrueden and @dietzc are currently fixing.  Without this fix the implementation becomes unnecessarily verbose and / or copy intense.  I suggest that @stelrich's implementation including everything that it does and depends on goes into Ops.

**Comment by tpietzsch** [comment]
@axtimwalde If your integral images will live in Ops, then that might make most sense indeed. Although I would also kind of like to have integral images in imglib...

**Comment by acardona** [comment]
@tpietzsch There is an ImgLib2-based integral image in the scripting package, purely ImgLib2, written years ago ... and I am sure that, in any case, a new one could be rewritten in little time.

**Comment by tpietzsch** [comment]
@acardona I know, that is already in imglib2-algorithm actually.
As far as I know @axtimwalde is trying to go beyond that, working toward "integral block images" that are split in blocks that each are an integral image. This would avoid that values in the integral image increase indefinitely (that would be especially relevant for one of our applications where pixel type is "Multi-set of Labels").

**Comment by axtimwalde** [comment]
@cardona thanks, and yes we are aware of this code, for the record https://github.com/imglib/imglib2-script/tree/master/src/main/java/net/imglib2/script/algorithm/integral the idea here, though, was to port the entirety of the code from integral generation to consuming code into the ops framework.  Personally, I want an entirely different access concept and the opportunity to store integral cell images that is not covered here.  But I am starting to get really nervous about this green merge button here.  Can we close this PR?  It's just not the right place to discuss incomplete ideas.

**Comment by acardona** [comment]
@tpietzsch Thanks for the explanations, integral block images sounds right. Been there, wrote the UnsignedLongType because of the issue.

**Comment by tpietzsch** [comment]
@axtimwalde if we move the `IntegralCursor` to ops, there will still remain the addition of `getSourceRandomAccess()` to `RectangleNeighborhood` in this PR.
@stelfrich can you split that out into a new PR or modify this one?

**Comment by stelfrich** [comment]
> can you split that out into a new PR or modify this one?

Will do.

> As a general remark (which probably no one will read buried in here, but anyway)

Put it in a _Contributing_ section of a README.md. And to be on the safe side, add a reminder in the first line of the default [PR template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/).

**Comment by tpietzsch** [comment]
@stelfrich 

> Put it in a Contributing section of a README.md. And to be on the safe side, add a reminder in the first line of the default PR template.

Thanks for the pointer! I didn't know about PR template

**Comment by hinerm** [comment]
>Thanks for the pointer! I didn't know about PR template

Me neither. That's awesome! Thanks @stelfrich

**Comment by ctrueden** [comment]
You can also [make a `CONTRIBUTING.md` file](https://github.com/blog/1184-contributing-guidelines) which is linked from the top of the PR creation screen. I agree with @stelfrich that this policy needs to be spelled out, since it is a social convention that varies by project. (Some projects, for example, encourage opening a PR as soon as possible so that all discussion can happen there.)

**Pull request closed without merging**
